#Dockerfile

FROM openjdk:21-jdk

cmd mkdir -p /opt
cmd mkdir -p /opt/conf


COPY target/authen-service-0.0.1-SNAPSHOT.jar /opt/authen-service-0.0.1-SNAPSHOT.jar
COPY src/main/resources/application.properties /opt/conf/application.properties
COPY src/main/resources/mail /opt/conf/mail

WORKDIR /opt

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/authen-service-0.0.1-SNAPSHOT.jar", "--spring.config.additional-location=/opt/conf/"]